import React, { useRef, useMemo } from 'react';
import ReactQuill from 'react-quill';
import { marked } from 'marked';
import 'react-quill/dist/quill.snow.css';
import { X, Save, Maximize2, Download, RefreshCcw, Printer } from 'lucide-react';

export default function Canvas({ content, onClose, onUpdate, isSaving }) {
  const quillRef = useRef(null);

  // Convert markdown to HTML for the rich text editor
  const htmlContent = useMemo(() => {
    if (content === null) return null;
    // If it already looks like HTML (starts with <), don't process
    if (content.trim().startsWith('<')) return content;
    return marked(content);
  }, [content]);

  // Allow rendering even with null/empty content
  const displayContent = htmlContent || '';

  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    const printContent = htmlContent || content;
    printWindow.document.write(`
      <html>
        <head>
          <title>AI Workspace Report</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
            body { font-family: 'Inter', -apple-system, sans-serif; padding: 50px; line-height: 1.6; color: #1a1a1a; max-width: 800px; margin: 0 auto; }
            h1 { font-size: 2.5rem; margin-bottom: 0.5rem; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
            h2 { font-size: 1.8rem; margin-top: 2rem; color: #2563eb; }
            h3 { font-size: 1.4rem; margin-top: 1.5rem; }
            p { margin-bottom: 1.2em; }
            ul, ol { margin-bottom: 1.2em; padding-left: 20px; }
            li { margin-bottom: 0.5em; }
            blockquote { border-left: 4px solid #e5e7eb; padding-left: 20px; font-style: italic; color: #4b5563; margin: 2rem 0; }
            code { background: #f3f4f6; padding: 0.2rem 0.4rem; border-radius: 4px; font-family: monospace; }
            pre { background: #1f2937; color: #f9fafb; padding: 1.5rem; border-radius: 8px; overflow-x: auto; margin: 1.5rem 0; }
            .print-footer { margin-top: 80px; font-size: 11px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 20px; display: flex; justify-content: space-between; }
            @media print {
              body { padding: 0; }
              .no-print { display: none; }
            }
          </style>
        </head>
        <body>
          <h1>AI Research Report</h1>
          <div class="content">${printContent}</div>
          <div class="print-footer">
            <span>Generated by Knowledge Base</span>
            <span>${new Date().toLocaleDateString('en-GB')} ${new Date().toLocaleTimeString('en-GB')}</span>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    // Wait for styles/fonts to load
    setTimeout(() => {
      printWindow.print();
    }, 500);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const printContent = htmlContent || content;
    const fileContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="UTF-8">
          <title>AI Research Report - ${new Date().toLocaleDateString()}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
            body { font-family: 'Inter', sans-serif; padding: 40px; line-height: 1.6; color: #1a1a1a; max-width: 900px; margin: 0 auto; background: #f9fafb; }
            .container { background: white; padding: 60px; border-radius: 12px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1); }
            h1 { color: #111827; border-bottom: 2px solid #3b82f6; padding-bottom: 12px; }
            .footer { margin-top: 40px; font-size: 12px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 20px; }
          </style>
        </head>
        <body>
          <div class="container">
            ${printContent}
            <div class="footer">Exported from Knowledge Base on ${new Date().toLocaleString('en-GB')}</div>
          </div>
        </body>
      </html>
    `;
    const file = new Blob([fileContent], {type: 'text/html'});
    element.href = URL.createObjectURL(file);
    element.download = `AI_Research_Report_${new Date().toISOString().split('T')[0]}.html`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const modules = {
    toolbar: [
      [{ 'header': [1, 2, 3, false] }],
      ['bold', 'italic', 'underline', 'strike'],
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      ['link', 'blockquote', 'code-block'],
      ['clean']
    ],
  };

  return (
    <div className="canvas-container">
      <div className="canvas-header">
        <div className="canvas-title">
          <RefreshCcw size={14} className={isSaving ? 'spin' : ''} />
          <span>AI Workspace</span>
        </div>
        <div className="canvas-actions">
          <button className="canvas-action-btn" title="Print Report" onClick={handlePrint}>
            <Printer size={16} />
          </button>
          <button className="canvas-action-btn" title="Download HTML" onClick={handleDownload}>
            <Download size={16} />
          </button>
          <button className="canvas-action-btn" title="Full Screen">
            <Maximize2 size={16} />
          </button>
          <button className="global-close-btn" onClick={onClose}>
            <X size={18} />
          </button>
        </div>
      </div>
      
      <div className="canvas-editor-wrapper rich-text">
        <ReactQuill 
          ref={quillRef}
          theme="snow"
          value={displayContent}
          onChange={onUpdate}
          modules={modules}
          placeholder="Detailed reports and summaries will appear here..."
        />
        <div className="canvas-preview-badge">Rich Text Editor</div>
      </div>
      
      <div className="canvas-footer">
        <span className="canvas-stats">
          {displayContent.replace(/<[^>]*>/g, '').split(/\s+/).filter(Boolean).length} words
        </span>
        <div style={{ display: 'flex', gap: '12px' }}>
          {isSaving && <span style={{ fontSize: '11px', opacity: 0.7 }}>Saving...</span>}
          <button className="canvas-save-btn">
            <Save size={14} style={{ marginRight: '6px' }} />
            Manual Save
          </button>
        </div>
      </div>
    </div>
  );
}
